### ISSUE TITLE
Add explicit dependency to scala-reflect

### ISSUE THREAD

**Issue by bhermann** [com-lihaoyi/fansi#17]
When just adding a dependency to fansi, once it is instantiated it throws the following error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: scala/reflect/api/TypeCreator
	at fansi.ColorCategory.$anonfun$Full$1(Fansi.scala:851)
	at fansi.ColorCategory.$anonfun$Full$1$adapted(Fansi.scala:850)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.Range.foreach(Range.scala:156)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at fansi.ColorCategory.<init>(Fansi.scala:850)
	at fansi.Color$.<init>(Fansi.scala:717)
	at fansi.Color$.<clinit>(Fansi.scala)
```

One can avoid this error by adding the following dependency to the project using fansi:
```
libraryDependencies += "org.scala-lang" % "scala-reflect" % scalaVersion.value
```

However, it would be ideal if it was already in the transitive dependencies of the original library.

**Comment by lihaoyi** [comment]
Seems like this is fixed some time between 0.5.3 and 0.6.6, closing
