### ISSUE TITLE
IllegalArgumentException: Unknown ansi-escape [2m

### ISSUE THREAD

**Issue by kpodsiad** [com-lihaoyi/fansi#46]
Summary

One of the Metals users hit an issue when Metals wasn't displaying errors which came from ZIO test suite. After an investigation I found that issue is caused by Fansi. ZIO sets [various ansi styles](https://github.com/zio/zio/blob/series/2.x/internal-macros/shared/src/main/scala/zio/internal/ansi.scala#L23-L28) in their tests and at least one of them (Faint - `"\u001b[2m"`) is unsupported by Fansi: 
```
Caused by: java.lang.IllegalArgumentException: Unknown ansi-escape [2m at index 206 inside string cannot be parsed into an fansi.Str`
```
In Metals, we use Fansi to [obtain plain text](https://github.com/scalameta/metals/blob/933a9d1562ce3ffd1e8fcddf04cd3f627b308160/metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala#L750-L760) from bsp diagnostic before forwarding it to the lsp client.

---

Reproduction

```scala
//> using scala "2.13.8"
//> using lib "com.lihaoyi::fansi:0.3.0"

object Fansi extends App {
  val Reset = "\u001b[0m"
  val Faint = "\u001b[2m"
  
  val byHand = Faint + "Foo" + Reset

  println("Foo")
  println(byHand)

  val plainText: fansi.Str = fansi.Str(byHand).plainText

  println(plainText)
}

```

---

Behavior

```scala
➜  scala-cli run Fansi.scala
Compiling project (Scala 2.13.8, JVM)
Compiled project (Scala 2.13.8, JVM)
Foo
Foo
Exception in thread "main" java.lang.IllegalArgumentException: Unknown ansi-escape [2m at index 0 inside string cannot be parsed into an fansi.Str
        at fansi.ErrorMode$Throw$.handle(Fansi.scala:440)
        at fansi.ErrorMode$Throw$.handle(Fansi.scala:428)
        at fansi.Str$.apply(Fansi.scala:280)
        at Fansi$.delayedEndpoint$Fansi$1(Fansi.scala:13)
        at Fansi$delayedInit$body.apply(Fansi.scala:4)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1(App.scala:76)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at Fansi$.main(Fansi.scala:4)
        at Fansi.main(Fansi.scala)
```

---

Expected Behavior

Fansi should parse `\u001b[2m` ansi code, as well as other styles defined in linked file from ZIO repository.

**Comment by kpodsiad** [comment]
Easy workaround for this issue - `fansi.Str(<string with ansi styles>, ErrorMode.Strip)`.

**Comment by jk-1** [comment]
I got same kind of exception message 

`java.lang.IllegalArgumentException: Unknown ansi-escape [0;93m at index 16 inside string cannot be parsed into an fansi.Str
`

when trying to run command `ssh-ping -q -W 2 -c 1 -p 22 myhost` with `os.proc(...)` which is part of [os.lib](https://github.com/com-lihaoyi/os-lib#os-proc-call). 

See [this](https://github.com/com-lihaoyi/os-lib/discussions/155) how to reproduce the error
